### ISSUE TITLE
Crash on user cancelling Google Pay native screen

### ISSUE THREAD

**Issue by bolekro** [zyra/capacitor-stripe#10]
If the user cancels the google pay method the app crashes with the following error:

> Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method > kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
        at ca.zyra.capacitor.stripe.Stripe.handleOnActivityResult(Unknown Source:2)

Please see my commit for a simple fix:
https://github.com/bolekro/capacitor-stripe/commit/42e229f96d7364f5629f95eb45207b0f4f3e7b8e

**Comment by JoshuvaGeorge03** [comment]
@ihadeed is this fix available latest release? I still have this issue. 

When the user cancelled google pay app is crashing.

**Comment by ihadeed** [comment]
Yes it's available in latest release (1.0.0-beta.0)

I haven't tried canceling the transaction though. If the issue persists I'll fix it ASAP.

**Comment by JoshuvaGeorge03** [comment]
@ihadeed thanks, I will check it out and let you know.
