### ISSUE TITLE
PaymentIntent missing from iOS?

### ISSUE THREAD

**Issue by jackbayliss** [zyra/capacitor-stripe#8]
Due to the European Law SCA is required, forcing us to use the Paymentintent API.
I noticed it's in the usage examples, however it seems completely missing in iOS

` ERROR: Method 'confirmSetupIntent:' not defined in Plugin 'CordovaStripe' `

I guess my question is- is iOS WIP? or am I completely missing something?

**Comment by ihadeed** [comment]
Plugin name is `Stripe`, not `CordovaStripe`.
